### ISSUE TITLE
can you provide a ng2+ or above version?

### ISSUE THREAD

**Issue by jamessawyer** [daveteply/ng-text-roll#4]
hey, the text roll effect is awesome, I'm wondering if you can provide a angular 2 or above version ? thx in advance!

**Comment by daveteply** [comment]
Hi James,

Thanks for the interest in my project!  Earlier this year I started my MBA
program so I haven't had much time to dedicate to ng-text-roll.  An Angular
version would be cool to build but also may require a different project
altogether.  I'll see if maybe I can take a peek over the holiday break.

Cheers!
-Dave

**Comment by jamessawyer** [comment]
thx for your reply,have a good day,LOL
